definitions:
  model.Profile:
    properties:
      birthYear:
        type: integer
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      secondName:
        type: string
      sex:
        type: boolean
      videoID:
        type: integer
    type: object
info:
  contact: {}
paths:
  /create_profile:
    post:
      consumes:
      - application/json
      description: Create profile
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Create profile
  /detele_profile:
    delete:
      consumes:
      - application/json
      description: Detele profile
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Detele profile
  /get_profile:
    post:
      consumes:
      - application/json
      description: Get profile
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Profile'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get profile
  /get_profiles:
    get:
      consumes:
      - application/json
      description: Get profiles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Profile'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get profiles
  /update_profile:
    put:
      consumes:
      - application/json
      description: Update profile info
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Update profile
swagger: "2.0"
